#!/bin/bash
export SCRAM_ARCH=slc6_amd64_gcc481
source /cvmfs/cms.cern.ch/cmsset_default.sh
if [ -r CMSSW_7_1_20/src ] ; then 
 echo release CMSSW_7_1_20 already exists
else
scram p CMSSW CMSSW_7_1_20
fi
cd CMSSW_7_1_20/src
eval `scram runtime -sh`

# curl -s --insecure https://cms-pdmv.cern.ch/mcm/public/restapi/requests/get_fragment/SMP-RunIIWinter15wmLHE-00070 --retry 2 --create-dirs -o Configuration/GenProduction/python/SMP-RunIIWinter15wmLHE-00070-fragment.py 
mkdir -p Configuration/GenProduction/python
cp /afs/cern.ch/work/s/sdeng/config_file/fragment/SMP-RunIIWinter15wmLHE-00070.py Configuration/GenProduction/python/
[ -s Configuration/GenProduction/python/SMP-RunIIWinter15wmLHE-00070.py ] || exit $?;

scram b
cd ../../
cmsDriver.py Configuration/GenProduction/python/SMP-RunIIWinter15wmLHE-00070.py  --fileout file:SMP-RunIIWinter15wmLHE-00070.root --mc --eventcontent LHE --datatier LHE --conditions MCRUN2_71_V1::All --step LHE --python_filename SMP-RunIIWinter15wmLHE-00070_1_cfg.py --no_exec --customise Configuration/DataProcessing/Utils.addMonitoring -n 10000 || exit $? ; 

